version: '2'

services:
  mongo:
        container_name: mongo
        image: mongo:latest
        volumes:
            - ./data/mongo:/data/db
        user: "501:20"
        ports:
            - "27017:27017"
        networks:
            - common
        restart: always
networks:
    common: